
// This file is generated by the webpack plugin DrupalTranslationsWebpackPlugin.
// It is required for Drupal to figure out which translations are needed,
// since its regex is unable to process minified webpack code.

function DrupalTranslationsWebpackPlugin () {
  
}
