<?php

/**
 * @file
 * Contains milken_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;


/**
 * Implements hook_help().
 */
function milken_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the milken_migrate module.
    case 'help.page.milken_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration classes and data for move to re-organized d8 site') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_migrate_prepare_row().
 */
function milken_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  //print_r($row);

}
