#!/usr/bin/env bash

## Initial container actions:

rm -Rf /var/www/html
ln -s /var/www/web /var/www/html
mkdir -p /var/www/web/sites/default/files
mkdir -p /var/www/web/sites/default/private
mkdir -p /var/www/web/sites/default/temp
touch /var/www/web/sites/default/files/.htaccess
touch /var/www/web/sites/default/private/.htaccess
touch /var/www/web/sites/default/temp/.htaccess


chown -R www-data:www-data /var/www/web/sites/default
chown www-data:www-data /var/www/web/sites/default/files/.htaccess
chown www-data:www-data /var/www/web/sites/default/private/.htaccess
chown www-data:www-data /var/www/web/sites/default/temp/.htaccess
chown www-data:www-data /var/www/web/vendor
chmod 755 /var/www/web/sites/default
chmod 755 /var/www/web/sites/default/files
chmod 755 /var/www/web/sites/default/temp
chmod 755 /var/www/web/sites/default/private

cd /root

curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install

cd /var/www/web
