<?php

namespace Drupal\milken_base\Plugin\Layout;

use Drupal\Core\Entity\Entity;
use Drupal\Core\Entity\EntityBase;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Layout\LayoutDefault;
use Drupal\Core\Layout\LayoutDefinition;
use Drupal\layout_builder\Context\LayoutBuilderContextTrait;
use Drupal\node\Entity\Node;

/**
 * A custom Layout for Milken "Slides".
 *
 * @Layout(
 *   id = "half_n_half",
 *   label = @Translation("Milken Half and Half"),
 *   category = @Translation("milken"),
 *   template = "templates/half-n-half",
 *   library = "milken/react-component",
 *   default_region = "content",
 *   icon = "images/half-n-half.png",
 *   regions = {
 *     "content" = {
 *       "label" = @Translation("React Coponent"),
 *     },
 *   },
 * )
 */
class HalfNHalf extends LayoutDefault {


  /**
   * @param array $regions
   *
   * @return array
   */
  function build(array $regions) {
    $toReturn = parent::build($regions); // TODO: Change the autogenerated stub
    if (!isset($toReturn['content']['#node'])) {
      $toReturn['content']['#node'] = \Drupal::routeMatch()->getParameter('node');
    }
    return $toReturn;
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    $form['label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Label'),
      '#default_value' => $this->configuration['label'],
    ];
    $form['layout_icon'] = [

    ];
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateConfigurationForm(array &$form, FormStateInterface $form_state) {
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    $this->configuration['label'] = $form_state->getValue('label');
  }

}
