<?php

/**
 * @file
 * Contains milken_base.module.
 */

/**
 * Implements hook_element_plugin_alter().
 */
function milken_base_element_plugin_alter(array &$definitions) {
  // \Kint::dump($definitions);
}


/**
 * Implements hook_theme_registry_alter().
 */
function milken_base_theme_registry_alter(&$theme_registry) {
  // TODO: obtain this list dynamically based on layout group
  $module_theme_hooks = ['one_col_full_width', 'half_n_half'];
  foreach ($theme_registry as $theme_hook => $registry_entry) {
    if (in_array($theme_hook, $module_theme_hooks)) {
      $theme_registry[$theme_hook]['preprocess functions'][] = 'milken_base_template_preprocess_layout_function';
    }
  }
}

function milken_base_template_preprocess_layout_function(&$variables) {
  $variables['content']['#node'] = \Drupal::routeMatch()->getParameter('node');
}
